import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import {
  faMoneyBill1,
  faDollarSign,
  faUsersGear,
  faBuilding,
  faMoneyCheck,
  faHandHoldingHeart,
  faMap,
  faWaterLadder,
  faBoltLightning,
  faChartLine,
  faFolderOpen,
  faChartPie,
  faRightLeft,
  faCoins,
  faGauge,
  faUsers,
  faFileLines,
  faGear,
  faBriefcase,
  faRightFromBracket,
  faHandshake,
  faEnvelope,
  faCheckToSlot,
  faUser
} from "@fortawesome/free-solid-svg-icons";
import Navlink from "./components/Navbar/Navlink/Navlink";
import NavlinkDropdown from "./components/Navbar/NavlinkDropdown/NavlinkDropdown";

import DropDownList from "./components/Navbar/NavlinkDropdown/DropdownList";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Capboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let DropListOwnership: Array<DropDownList> = [
    { name: "Transaction", icon: faRightLeft, href: "/transaction" },
    { name: "Cap Table", icon: faChartPie, href: "/captable" },
    { name: "Share Classes", icon: faFolderOpen, href: "/shareclasses" },
    { name: "Simulations", icon: faChartLine, href: "/simulations" },
  ];

  let DropListEquityPlans: Array<DropDownList> = [
    { name: "Pools", icon: faWaterLadder, href: "/pool" },
    { name: "Plans", icon: faMap, href: "/plans" },
    { name: "Grants", icon: faHandHoldingHeart, href: "/grants" },
    { name: "Exercising", icon: faMoneyCheck, href: "/exercising" },
  ];

  let DropListInvestorRelations: Array<DropDownList> = [
    { name: "Updates", icon: faEnvelope, href: "/updates" },
    { name: "Meetings", icon: faCheckToSlot, href: "/meetings" },
  ];

  let DropListCompany: Array<DropDownList> = [
    { name: "Settings", icon: faGear, href: "/company_settings" },
    { name: "Collabrators", icon: faUsersGear, href: "/collabrators" },
    { name: "Subscription", icon: faDollarSign, href: "/subscription" },
  ];


  return (
    <html lang="en">
      <body>
        <aside className="navbar-aside">
          <ul className="navbar-ul">
            <h2>Capboard</h2>
            <Navlink name="Dashboard" href="/dashboard" icon={faGauge} />
            <Navlink name="Stakeholders" href="/stakeholders" icon={faUsers} />
            <NavlinkDropdown name="Ownership" icon={faCoins} Navlinks={DropListOwnership} />
            <NavlinkDropdown name="Equity Plans" icon={faBoltLightning} Navlinks={DropListEquityPlans} />
            <NavlinkDropdown name="Investor relations" icon={faHandshake} Navlinks={DropListInvestorRelations} />
            <Navlink name="Documents" href="/documents" icon={faFileLines} />
            <NavlinkDropdown name="Company" icon={faBuilding} Navlinks={DropListCompany} />
            <Navlink name="Portfolio" href="/portfolio" icon={faBriefcase} />
            <Navlink name="Account Settings" href="/accountsettings" icon={faGear} />
            <Navlink name="Logout" href="/logout" icon={faRightFromBracket} />
          </ul>
        </aside>

        <main className="main-content">{children}</main>
      </body>
    </html>
  );
}
