'use client';

import './transaction.css';
import React, { useState } from 'react';
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faPlus, faSearch } from "@fortawesome/free-solid-svg-icons";
import { Box, Modal } from '@mui/material';
import ModalBoxT from './ModalBox';
import Head from 'next/head';

const Page = () => {

  const [openModal, setOpenModal] = useState(false);

  const closeModal = () => {
    setOpenModal(false);
  };

  return (
    <div className="container">
      <Modal open={openModal} onClose={closeModal}>
        <Box>
          <ModalBoxT CloseModal={closeModal} />
        </Box>
      </Modal>

      <Head>
        <title>Transactions Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="main">
        <div className="header">
          <h1 className="title">Transactions</h1>
          <p className="description">Manage dfsfsdfsfsd’s transactions.</p>
        </div>

        <div className="filters">
          <div className="filterItem">
            <label>Stakeholder</label>
            <select className="select">
              <option value="">Select...</option>
              <option>Ali Bay</option>
            </select>
          </div>

          <div className="filterItem">
            <label>Transaction type</label>
            <select className="select">
              <option value="">Select...</option>
              <option>Valuation</option>
              <option>Issue</option>
              <option>Convertible Loan</option>
              <option>Transfer</option>
              <option>Grant</option>
              <option>Payout</option>
              <option>Pool creation</option>
              <option>Pool increase</option>
              <option>Pool decrease</option>
              <option>Split</option>
              <option>Buy back</option>
              <option>Decrease Shares</option>
            </select>
          </div>

          <div className="filterItem">
            <label>Date lower than</label>
            <input type="date" placeholder="gg.aa.yyyy" className="input" />
          </div>

          <button className="searchButton">
            <FontAwesomeIcon icon={faSearch} /> Search
          </button>
        </div>

        <button className="addButton" onClick={() => setOpenModal(true)}>
          <FontAwesomeIcon icon={faPlus} /> ADD TRANSACTION
        </button>

        <div className="transactions">
          <div className="transaction">
            <div className="date">2024-07-05</div>
            <div className="details">
              <div className="id">#107952</div>
              <div className="type grant">Grant</div>
              <div className="name">Ali Bay</div>
              <div className="info">+12 Phantoms</div>
              <div className="actions">
                <button className="editButton">✏️ Edit</button>
                <button className="deleteButton">🗑 Delete</button>
              </div>
            </div>
          </div>

          <div className="transaction">
            <div className="date">2024-05-31</div>
            <div className="details">
              <div className="id">#107044</div>
              <div className="type pool">Pool</div>
              <div className="name">dksdfds</div>
              <div className="info">2,324 shares</div>
              <div className="info">Common</div>
              <div className="actions">
                <button className="editButton">✏️ Edit</button>
                <button className="deleteButton">🗑 Delete</button>
              </div>
            </div>
          </div>

          <div className="transaction">
            <div className="date">2024-07-05</div>
            <div className="details">
              <div className="id">#107045</div>
              <div className="type equity">Equity plan</div>
              <div className="name">fdfgdfgd</div>
              <div className="info">dksdfds</div>
              <div className="actions">
                <button className="editButton">✏️ Edit</button>
                <button className="deleteButton">🗑 Delete</button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Page;
